name: Update Repos

on:
  schedule:
    - cron: '0 0 * * *'     # Every 24 hours
  workflow_dispatch:        # Optional manual trigger from GitHub UI

jobs:
  update-repos:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Dependencies
        working-directory: ./backend
        run: npm install

      - name: Run Update Script
        working-directory: ./backend
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
        run: node scripts/updateRepos.js