name: Update Repos

on:
  schedule:
    - cron: "0 0 * * *" # Every 24 hours
  workflow_dispatch: # Optional manual trigger from GitHub UI

jobs:
  update-repos:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Dependencies
        run: npm install

      - name: Run Update Script
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
        run: node scripts/updateRepos.js
